### ISSUE TITLE
cs.getMsgToken of genki.js needs to use token for authentication

### ISSUE THREAD

**Issue by dixonsiu** [fujitsu-pio/calorie-smile-app#3]

**Comment by csKyou** [comment]
Comment out the processing of grant_type: "password" of cs.getMsgToken and use the processing of grant_type: "refresh_token".
Just by making the above changes cs.getMsgToken will work.

For refresh processing, please acquire the token by executing cs.getAppToken () → cs.getMsgToken () and store it as shown below.
 cs.accessData.token = Acquired access token
 cs.accessData.refToken = The acquired refresh token

**Comment by dixonsiu** [comment]
After talking to Sakamoto-san directly, the followings were updated.

To fix cs.getMsgToken, the followings were applied.
1. [Replace grant_type by refresh_token](https://github.com/dixonsiu/calorie-smile-app/commit/4d2bb5cd8af46f9f01881fae4acbb5e1f9da1721)
1. [Replace user/password by refresh token](https://github.com/dixonsiu/calorie-smile-app/blob/master/src/js/genki.js#L911)

The "For refreshing processing ..." part is in fact the answer for #4.
